### **dataset_2_macro_brent_oil_daily**

In [2]:
pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

##### **Date Formate -> YYYY-MM-DD eg. 2026-01-9**

In [ ]:
import pandas as pd

# df = pd.read_csv("dataset_2_macro_brent_oil_daily.csv")
df = pd.read_csv("dataset_1_freight_bdi_daily.csv")

# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df.head()

# df.to_csv("dataset_1_freight_bdi_daily.csv", index=False)

df.tail()

/tmp/ipykernel_17483/1868449636.py:6: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

           Date     Price      Open      High       Low  Vol. Change %
3898 2011-01-10  1,495.00  1,495.00  1,495.00  1,495.00   NaN   -1.58%
3899 2011-01-07  1,519.00  1,519.00  1,519.00  1,519.00   NaN   -1.62%
3900 2011-01-06  1,544.00  1,544.00  1,544.00  1,544.00   NaN   -4.75%
3901 2011-01-05  1,621.00  1,621.00  1,621.00  1,621.00   NaN   -4.25%
3902 2011-01-04  1,693.00  1,693.00  1,693.00  1,693.00   NaN   -4.51%

In [22]:
df = pd.read_csv("dataset_2_macro_brent_oil_daily.csv")

df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y").dt.strftime("%Y-%m-%d")

df.to_csv("dataset_2_macro_brent_oil_daily.csv", index=False)
df.head()

         Date  Price   Open   High    Low     Vol. Change %
0  2026-09-04  96.28  95.95  96.57  93.15  316.03K    0.80%
1  2026-09-03  95.52  95.19  97.62  94.03  406.59K   -0.12%
2  2026-09-02  95.63  95.25  97.04  93.52  354.54K    1.04%
3  2026-09-01  94.65  90.81  95.45  90.70  425.10K    4.60%
4  2026-08-31  90.49  89.45  91.52  89.03  233.39K    2.71%

In [55]:
df = pd.read_csv("dataset_2_macro_usd_inr_daily.csv")
# df.to_csv("dataset_2_macro_coal_newcastle_daily.csv", index=False)
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y").dt.strftime("%Y-%m-%d")
# df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df.to_csv("dataset_2_macro_usd_inr_daily.csv", index=False)

df.head()

         Date   Price    Open    High     Low  Vol. Change %
0  2026-09-04  94.490  94.490  94.525  94.455   NaN    0.00%
1  2026-09-03  94.490  94.305  94.496  94.290   NaN   -0.51%
2  2026-09-02  94.975  94.960  94.980  94.845   NaN    0.02%
3  2026-09-01  94.960  95.005  95.100  94.800   NaN   -0.22%
4  2026-08-31  95.167  95.495  95.495  95.110   NaN   -0.22%

In [64]:
df = pd.read_csv("dataset_8_disruption_events.csv")

df.drop(columns=["event_date"], inplace=True)
df.to_csv("dataset_8_disruption_events.csv", index=False)
df.head()

,port_name,country,event_type,impact_days,notes
0,Paradip,India,cyclone,3,Cyclone Yaas landfall near Odisha–West Bengal;...
1,Haldia Dock Complex,India,cyclone,2,Cyclone Yaas caused tidal surge at Haldia; ope...
2,Haldia Dock Complex,India,cyclone,2,Cyclone Remal landfall near West Bengal/Bangla...
3,Paradip,India,severe_weather,1,Cyclone Remal brought squally winds to Bay of ...
4,Haldia Dock Complex,India,cyclone,3,Super Cyclone Amphan; Haldia operations suspen...